def Self(id, params, players, mud):
	mud.send_message(id, "==================================================")
	mud.send_message(id, "|| Name:	     {}              			      ||".format(players[id].name))
	mud.send_message(id, "|| Race:	     {}			   Gender:	    {}    ||".format(players[id].race.capitalize(), players[id].gender.capitalize()))
	mud.send_message(id, "|| Description: {} {}                           ||".format(players[id].name, players[id].description))
	mud.send_message(id, "||----------------------------------------------||")
	mud.send_message(id, "|| Gold: 		 {}								  ||".format(players[id].gold))
	mud.send_message(id, "||----------------------------------------------||")
	mud.send_message(id, "|| Strength:   {}         Mining:          {}    ||".format(players[id].strength, players[id].mining))
	mud.send_message(id, "|| Dexterity:  {}         Fishing:         {}    ||".format(players[id].dexterity, players[id].fishing))
	mud.send_message(id, "|| Wisdom:     {}         Foresting:       {}    ||".format(players[id].wisdom, players[id].foresting))
	mud.send_message(id, "||                       Cooking:         {}    ||".format(players[id].cooking))
	mud.send_message(id, "|| Endurance:  {}         Blacksmithing:   {}    ||".format(players[id].endurance, players[id].blacksmithing))
	mud.send_message(id, "|| Clarity:    {}         Rangership:      {}    ||".format(players[id].clarity, players[id].rangership))
	mud.send_message(id, "||  			             Energycraft:     {}    ||".format(players[id].energycraft))
	mud.send_message(id, "||----------------------------------------------||")
	mud.send_message(id, "|| Main:       {}		   Off-hand:		{}    ||".format(players[id].weapon1, players[id].weapon2))
	mud.send_message(id, "|| Helmet: 	 {}		   Cloak:			{}    ||".format(players[id].helmet, players[id].cloak))
	mud.send_message(id, "|| Chest: 	 {}        Gloves: 			{}    ||".format(players[id].chest, players[id].gloves))
	mud.send_message(id, "|| Legs:       {}        Boots: 			{}    ||".format(players[id].legs, players[id].boots))
	mud.send_message(id, "|| Necklace:   {}        Ring: 			{}    ||".format(players[id].necklace, players[id].ring))
	mud.send_message(id, "==================================================")
	mud.send_message(id, "")