import math

def Self(id, params, players, mud):
	mud.send_message(id, "==============================================================")
	mud.send_message(id, "|| Name:	     {}              			                  ||".format(players[id].name))
	mud.send_message(id, "|| Race:	     {}			   Gender:	    {}                ||".format(players[id].race.capitalize(), players[id].gender.capitalize()))
	mud.send_message(id, "|| Description: {} {}                                       ||".format(players[id].name, players[id].description))
	mud.send_message(id, "||----------------------------------------------------------||")
	mud.send_message(id, "|| Gold: 		 {}								              ||".format(players[id].gold))
	mud.send_message(id, "||----------------------------------------------------------||")
	mud.send_message(id, "|| Strength:   {} ({}xp/{}xp)        Mining:          {}    ||".format(players[id].strength, players[id].strengthxp, str(math.ceil((players[id].strength + 1) ** 2.1 * 100)), players[id].mining))
	mud.send_message(id, "|| Dexterity:  {} ({}xp/{}xp)        Fishing:         {}    ||".format(players[id].dexterity, players[id].dexterityxp, str(math.ceil((players[id].dexterity + 1) ** 2.1 * 100)), players[id].fishing))
	mud.send_message(id, "|| Wisdom:     {} ({}xp/{}xp)        Foresting:       {}    ||".format(players[id].wisdom, players[id].wisdomxp, str(math.ceil((players[id].wisdom + 1) ** 2.1 * 100)), players[id].foresting))
	mud.send_message(id, "||                                  Cooking:         {}     ||".format(players[id].cooking))
	mud.send_message(id, "|| Endurance:  {} ({}xp/{}xp)        Blacksmithing:   {}    ||".format(players[id].endurance, players[id].endurancexp, str(math.ceil((players[id].endurance + 1) ** 2.1 * 100)), players[id].blacksmithing))
	mud.send_message(id, "|| Clarity:    {} ({}xp/{}xp)        Rangership:      {}    ||".format(players[id].clarity, players[id].clarityxp, str(math.ceil((players[id].clarity + 1) ** 2.1 * 100)), players[id].rangership))
	mud.send_message(id, "||  			                      Energycraft:     {}    ||".format(players[id].energycraft))
	mud.send_message(id, "||----------------------------------------------------------||")
	mud.send_message(id, "|| Main:       {}		   Off-hand:		{}                ||".format(players[id].weapon1, players[id].weapon2))
	mud.send_message(id, "|| Helmet: 	 {}		   Cloak:			{}                ||".format(players[id].helmet, players[id].cloak))
	mud.send_message(id, "|| Chest: 	 {}        Gloves: 			{}                ||".format(players[id].chest, players[id].gloves))
	mud.send_message(id, "|| Legs:       {}        Boots: 			{}                ||".format(players[id].legs, players[id].boots))
	mud.send_message(id, "|| Necklace:   {}        Ring: 			{}                ||".format(players[id].necklace, players[id].ring))
	mud.send_message(id, "==============================================================")
	mud.send_message(id, "")