import math

def Self(id, params, players, mud):

	name = 			"Name: {}".format(players[id].name)
	race = 			"Race: {}".format(players[id].race.capitalize())
	gender = 		"Gender: {}".format(players[id].gender.capitalize())
	description = 	"Description: {} {}".format(players[id].name, players[id].description)
	gold = 			"Gold: {}".format(players[id].gold)
	strength = 		"Strength:  {} ({}xp/{}xp)".format(players[id].strength, players[id].strengthxp, str(math.ceil((players[id].strength + 1) ** 2.1 * 100)))
	dexterity = 	"Dexterity: {} ({}xp/{}xp)".format(players[id].dexterity, players[id].dexterityxp, str(math.ceil((players[id].dexterity + 1) ** 2.1 * 100)))
	wisdom = 		"Wisdom:    {} ({}xp/{}xp)".format(players[id].wisdom, players[id].wisdomxp, str(math.ceil((players[id].wisdom + 1) ** 2.1 * 100)))
	endurance = 	"Endurance: {} ({}xp/{}xp)".format(players[id].endurance, players[id].endurancexp, str(math.ceil((players[id].endurance + 1) ** 2.1 * 100)))
	clarity = 		"Clarity:   {} ({}xp/{}xp)".format(players[id].clarity, players[id].clarityxp, str(math.ceil((players[id].clarity + 1) ** 2.1 * 100)))
	mining = 		"Mining:        {} ({}xp/{}xp)".format(players[id].mining, players[id].miningxp, str(math.ceil((players[id].mining + 1) ** 2.1 * 100)))
	fishing = 		"Fishing:       {} ({}xp/{}xp)".format(players[id].fishing, players[id].fishingxp, str(math.ceil((players[id].fishing + 1) ** 2.1 * 100)))
	foresting = 	"Foresting:     {} ({}xp/{}xp)".format(players[id].foresting, players[id].forestingxp, str(math.ceil((players[id].foresting + 1) ** 2.1 * 100)))
	cooking = 		"Cooking:       {} ({}xp/{}xp)".format(players[id].cooking, players[id].cookingxp, str(math.ceil((players[id].cooking + 1) ** 2.1 * 100)))
	blacksmithing = "Blacksmithing: {} ({}xp/{}xp)".format(players[id].blacksmithing, players[id].blacksmithingxp, str(math.ceil((players[id].blacksmithing + 1) ** 2.1 * 100)))
	rangership = 	"Rangership:    {} ({}xp/{}xp)".format(players[id].rangership, players[id].rangershipxp, str(math.ceil((players[id].rangership + 1) ** 2.1 * 100)))
	energycraft = 	"Energycraft:   {} ({}xp/{}xp)".format(players[id].energycraft, players[id].energycraftxp, str(math.ceil((players[id].energycraft + 1) ** 2.1 * 100)))

	main = 			"Main:     {}".format(players[id].weapon1)
	offhand = 		"Off-hand: {}".format(players[id].weapon2)
	helmet = 		"Helmet:   {}".format(players[id].helmet)
	cloak = 		"Cloak:    {}".format(players[id].cloak)
	chest = 		"Chest:    {}".format(players[id].chest)
	gloves = 		"Gloves:   {}".format(players[id].gloves)
	legs = 			"Legs:     {}".format(players[id].legs)
	boots = 		"Boots:    {}".format(players[id].boots)
	necklace = 		"Necklace: {}".format(players[id].necklace)
	ring = 			"Ring:     {}".format(players[id].ring)
	
	mud.send_message(id, "======================================================================================")
	mud.send_message(id, "|| {:<80} ||".format(name))
	mud.send_message(id, "|| {:<39} {:<40} ||".format(race, gender))
	mud.send_message(id, "|| {:<80} ||".format(description))
	mud.send_message(id, "||----------------------------------------------------------------------------------||")
	mud.send_message(id, "|| {:<80} ||".format(gold))
	mud.send_message(id, "||----------------------------------------------------------------------------------||")
	mud.send_message(id, "|| {:<39} {:<40} ||".format(strength, endurance))
	mud.send_message(id, "|| {:<39} {:<40} ||".format(dexterity, clarity))
	mud.send_message(id, "|| {:<80} ||".format(wisdom))
	mud.send_message(id, "||----------------------------------------------------------------------------------||")
	mud.send_message(id, "|| {:<39} {:<40} ||".format(mining, fishing))
	mud.send_message(id, "|| {:<39} {:<40} ||".format(foresting, cooking))
	mud.send_message(id, "|| {:<39} {:<40} ||".format(blacksmithing, rangership))
	mud.send_message(id, "|| {:<80} ||".format(energycraft))
	mud.send_message(id, "||----------------------------------------------------------------------------------||")
	mud.send_message(id, "|| {:<39} {:<40} ||".format(main, offhand))
	mud.send_message(id, "|| {:<39} {:<40} ||".format(helmet, cloak))
	mud.send_message(id, "|| {:<39} {:<40} ||".format(chest, legs))
	mud.send_message(id, "|| {:<39} {:<40} ||".format(gloves, boots))
	mud.send_message(id, "|| {:<39} {:<40} ||".format(necklace, ring))
	mud.send_message(id, "======================================================================================")
	mud.send_message(id, "")